### ISSUE TITLE
generate command produces an invalid fqn

### ISSUE THREAD

**Issue by kpob** [odradev/cargo-odra#70]
The command 

```bash
cargo odra generate -c erc20
# or
# cargo odra generate -c Erc20
```
generates
```toml
[[contracts]]
fqn = "my_project::Erc20::Erc20"
```
should generate
```toml
[[contracts]]
fqn = "my_project::erc20::Erc20"
```
