### ISSUE TITLE
Update `odra` source.

### ISSUE THREAD

**Issue by zie1ony** [odradev/cargo-odra#88]
Allow to update `odra` source between local, git and crates.io like:
```
cargo odra set-odra --git ... --branch
cargo odra set-odra <path>
cargo odra set-odra <version>
```

This should help: https://github.com/killercup/cargo-edit

**Comment by kubaplas** [comment]
There is a lighter way than rewriting `Cargo.toml`: Cargo reads `[patch.crates-io]` from `.cargo/config.toml`, so the project's manifest never changes. Verified on a project generated against odra 2.9.1 from crates.io:

```toml
# .cargo/config.toml
[patch.crates-io]
odra = { path = "/home/me/odra/odra" }
odra-test = { path = "/home/me/odra/odra-test" }
odra-build = { path = "/home/me/odra/odra-build" }
odra-cli = { path = "/home/me/odra/odra-cli" }
```

then `cargo update -p odra -p odra-test -p odra-build -p odra-cli`, and `cargo odra test` compiled every odra crate from the local checkout.

Two rules make it work: every odra crate the project depends on directly has to be patched (otherwise you get two copies of `odra-core` and type errors), and `cargo update` for those crates is required whenever the patched version differs from the one in `Cargo.lock`.

That reduces this issue to a small command that writes that file for exactly the odra crates in the project's manifest and runs the `cargo update`, with `local <path>`, `git <repo> [--branch]` and `reset` variants. No manifest rewriting, no `toml_edit`, and it works the same for workspaces and single crates. Parking the decision here.
